import Head from 'next/head'
import { ReactNode } from 'react'
import MainNav from './MainNav'

interface Props {
  children?: ReactNode,
  title?: string
}

const renderTitle = (title:string|undefined) => {
  let r = "Michael Lloyd Morris";
  if (title) r += ` - ${title}`;
  return <title>{r}</title>
}

export default function Page({children, title}:Props) {
  return (
    <>
      <Head>
        {renderTitle(title)}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainNav />
      <main>
        {children}
      </main>
      <footer className="main">
        <p>&copy; {new Date().getFullYear()} Michael Lloyd Morris</p>
        <p>Hosted by Vercel.</p>
      </footer>
    </>
  )
}