import Head from 'next/head'
import { ReactNode } from 'react'
import MainNav from './MainNav'

interface Props {
  children?: ReactNode,
  title?: string
}

const renderSubTitle = (title:string|undefined) => {
  return title ? `- ${title}` : "";
}

export default function Page({children, title}:Props) {
  return (
    <>
      <Head>
        <title>Michael Lloyd Morris {renderSubTitle(title)}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainNav />
      <main>
        {children}
      </main>
    </>
  )
}