import '@/styles/globals.scss'
import type { AppProps } from 'next/app'
import { QueryClient, QueryClientProvider } from "@tanstack/react-query"

import MainNav from '@/components/MainNav';
import Head from 'next/head';
import PageTransition from '@/components/PageTransition';

const queryClient = new QueryClient();

export default function App({ Component, pageProps }: AppProps) {

  return (
    <QueryClientProvider client={queryClient}>
      <Head>
        <title>Michael Lloyd Morris&apos; Portfolio Site</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta property="og:title" content="Michael Lloyd Morris' Portfolio Site" />
        <meta property="og:description" content="Veteran code monkey looking for work." />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainNav />
      <PageTransition>
        <Component {...pageProps} />
      </PageTransition> 
    </QueryClientProvider>
  )
}
