import "@/styles/globals.scss";
import type { AppProps } from "next/app";
import { SessionProvider } from "next-auth/react";
import { Session } from "next-auth";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { defaultTheme, Provider } from "@adobe/react-spectrum";

import Head from "next/head";
import PageTransition from "@/components/PageTransition";

const queryClient = new QueryClient();

export default function App({
  Component,
  pageProps: { session, ...pageProps },
}: AppProps<{ session: Session }>) {
  return (
    <SessionProvider session={session}>
      <QueryClientProvider client={queryClient}>
        <Head>
          <title>Michael Lloyd Morris&apos; Portfolio Site</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <meta
            property="og:title"
            content="Michael Lloyd Morris' Portfolio Site"
          />
          <meta
            property="og:description"
            content="I am a full stack developer with 19 year's experience currently looking for work on NodeJS, ReactJS, or Drupal websites."
          />
          <meta
            property="og:image"
            content="https://mmorris-sandbox.net/img/og-image.png"
          />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Provider theme={defaultTheme}>
          <PageTransition>
            <Component {...pageProps} />
          </PageTransition>
        </Provider>
      </QueryClientProvider>
    </SessionProvider>
  );
}
